HSC-57: Add eip config
CRUDEM/bahmni-distro-hsc pull request #4
Opened 2021-12-14 11:23 UTC by chinzou

https://mekomsolutions.atlassian.net/browse/HSC-57

2021-12-14 14:03 UTC, rbuisson requested changes

2021-12-14 14:03 UTC, rbuisson commented on pom.xml
> +    <eipRoutesOdoo>1.0-SNAPSHOT</eipRoutesOdoo>
`eipRoutesOdooVersion`

2021-12-14 14:03 UTC, rbuisson commented on eip_config/config/application.properties
> +oauth.enabled=true
I don't think we should have this set to `true`

2021-12-14 14:03 UTC, rbuisson commented on eip_config/config/senaite-config/application.properties
> +# *********************** General EIP sender properties ****************************************************************
Is this file needed at all?

2021-12-14 14:16 UTC, chinzou commented on eip_config/config/senaite-config/application.properties
> +# *********************** General EIP sender properties ****************************************************************
This file is not needed at all.

2021-12-23 09:18 UTC, rbuisson requested changes

2021-12-23 09:18 UTC, rbuisson commented on eip_config/config/application.properties
>  #The client Id of the account
Should those be removed? or set to empty maybe?

2021-12-23 09:18 UTC, rbuisson commented on eip_config/config/application.properties
> +eip.watchedTables=orders,test_order
Could you make sure to watch the right tables?
As discussed the other day I believe Odoo routes need to watch more than those 2 tables: See https://github.com/mekomsolutions/eip-routes-odoo/blob/87ea7b58561f2fa961cc347eac7f019e0e5c1e3f/src/test/resources/application.properties#L6

2021-12-23 09:18 UTC, rbuisson commented on pom.xml
> +    <eipRoutesOdooVersion>1.0-SNAPSHOT</eipRoutesOdooVersion>
Let's use `1.0.0-SNAPSHOT`

2022-01-06 14:51 UTC, merged